"""Seed a working checkout for one role, and freeze what the role changed.

A role — `oracle`, `naive`, or any extra variant — gets its own copy of the
curator checkout to edit, and produces a fixture: a patch plus a short applier
taking the checkout path. That is the calling convention
`failed_tasks/BRACKET.md` and `failed_tasks/_suites/bracket_matrix.txt` already use
(`python3 fixtures/oracle.py <checkout>`), so nothing downstream has to learn a
new shape — but the patch is generated from what the agent actually did rather
than hand-written, which is what makes this scale past one task.

The host `curator/` and `devbox:/opt/world-state/input/curator` have
**byte-identical `src/` trees** (verified by hash) and the container copy carries
its own `.git`, so a diff taken here applies there.

**Only `src/` is frozen.** An authoring agent may well leave notes or scratch
tests behind, and curator's own `tests/` is not what grades this task — our suite
is. Scoping the patch to the source tree keeps the fixture to the thing under
measurement, and keeps a role from accidentally shipping a test that agrees with
its own mistake.
"""
from __future__ import annotations

import pathlib
import shutil
import subprocess
import tempfile

from .model import REPO

SOURCE = REPO / "curator"
# Persistent trees, for roles that are allowed to see everything.
PERSISTENT = REPO / "task_generator" / ".trees"

APPLIER = '''#!/usr/bin/env python3
"""Apply the {role} fixture to a checkout.  Generated by task_generator."""
import pathlib
import subprocess
import sys

PATCH = pathlib.Path(__file__).with_suffix(".patch")


def main(root: str) -> int:
    if not PATCH.is_file():
        print("no patch beside " + __file__, file=sys.stderr)
        return 2
    if not PATCH.read_text().strip():
        return 0                      # an empty change is a legitimate fixture
    done = subprocess.run(["git", "apply", "--whitespace=nowarn", str(PATCH)],
                          cwd=root, capture_output=True, text=True)
    if done.returncode != 0:
        print(done.stderr.strip()[:2000], file=sys.stderr)
    return done.returncode


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1]))
'''


def _git(tree: pathlib.Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    done = subprocess.run(["git", "-C", str(tree), *args], capture_output=True, text=True)
    if check and done.returncode != 0:
        raise SystemExit(f"git {' '.join(args[:2])} in {tree}: {done.stderr.strip()[:400]}")
    return done


def seed(slug: str, role: str, *, fresh: bool = True, isolated: bool = False) -> pathlib.Path:
    """A clean checkout for `role` to work in.

    `isolated=True` puts the tree in a system temp directory instead of under
    this repo, and is how the **naive** role is built. That role's entire value is
    not knowing the hidden requirements, and they are sitting in
    `out/<slug>/facts.json` — three `..` away from a tree under `.trees/`. An
    agent has no reason to look there, but "no reason" is not a guarantee, and
    contamination would silently invalidate the one measurement the whole package
    exists to make. From a temp directory the answer key is not reachable by any
    relative path, and the prompt never names an absolute one.

    Asymmetric on purpose: `oracle` is handed the whole specification anyway, so
    isolating it would buy nothing and would cost the test writer a tree to read.
    """
    if not (SOURCE / ".git").is_dir():
        raise SystemExit(f"{SOURCE} is not a git checkout")
    if isolated:
        tree = pathlib.Path(tempfile.mkdtemp(prefix=f"tg-{role}-")) / "curator"
    else:
        tree = PERSISTENT / slug / role
        if tree.exists():
            if not fresh:
                return tree
            shutil.rmtree(tree)
    tree.parent.mkdir(parents=True, exist_ok=True)
    # A plain copy, not a clone: the role must see the working tree exactly as an
    # engineer in the world sees it.
    shutil.copytree(SOURCE, tree, symlinks=True)
    _git(tree, "reset", "--hard", "HEAD", check=False)
    _git(tree, "clean", "-fdx", "src", check=False)
    return tree


def freeze(task_dir: pathlib.Path, role: str, tree: pathlib.Path) -> tuple[pathlib.Path, int]:
    """Turn `trees/<role>` into `fixtures/<role>.{patch,py}`.

    Returns the patch path and its line count, so a caller can say out loud when
    a role produced no change at all — which is a real outcome (a naive build
    that decided nothing was needed) and must not look like success.
    """
    if not tree.is_dir():
        raise SystemExit(f"no tree at {tree}; run `tg build {task_dir.name} --role {role}` first")

    subprocess.run(["find", str(tree / "src"), "-name", "__pycache__", "-type", "d",
                    "-prune", "-exec", "rm", "-rf", "{}", "+"], capture_output=True)
    _git(tree, "add", "-A", "src")
    diff = _git(tree, "diff", "--cached", "--binary", "--", "src").stdout

    fixtures = task_dir / "fixtures"
    fixtures.mkdir(parents=True, exist_ok=True)
    patch = fixtures / f"{role}.patch"
    patch.write_text(diff)
    applier = fixtures / f"{role}.py"
    applier.write_text(APPLIER.format(role=role))
    applier.chmod(0o755)
    return patch, len(diff.splitlines())
