"""Pool every task's reader verdicts into the cross-task numbers for the report.

Counts only; every verdict here was made by a reader reading a transcript, and every
override is the one aggregate.py applies (so the per-task and pooled figures agree).
Pass/fail comes from Horizon's grade in the prepass, never from a reader.
A task in THIN (too few scored runs) is reported beside the pool, never inside it.
"""
import collections, glob, json, os, re, sys

S = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, S)
import aggregate as A  # OVERRIDES, NEVER_SHIPPED, norm_found, yes

REPO = "/home/nidhi_bespokelabs_ai/SWEWorld"
T = json.load(open(f"{S}/targets.json"))
THIN = set()  # g9 was n=2 (v7, 8/10 errored) until its v8 eval, 10/10 scored, replaced it on 2026-09-11
KNOWLEDGE = {"not_found", "found_misread", "herring_followed", "overridden_by_other_corpus_text",
             "grader_overspecifies", "implementation_slip", "borderline_unstated_order"}


def pct(n, d):
    return f"{n}/{d} ({100 * n / d:.0f}%)" if d else "—"


def plant_carriers(slug):
    p = f"{REPO}/task_generator/out/{slug}/clues/plant.json"
    out = {}
    for t in json.load(open(p))["tasks"]:
        for r in t["requirements"]:
            for c in r["clues"]:
                car = c.get("carrier") or {}
                out[c["clue_id"]] = {"carrier_kind": car.get("kind"), "channel": car.get("channel") or car.get("room")}
    return out


def load(g):
    pre = json.load(open(f"{S}/prepass/{g}.json"))
    meta = {r["id"]: r for r in pre["remarks"]}
    plant = plant_carriers(T[g]["slug"])
    runs = []
    for f in glob.glob(f"{S}/readers/{g}/run*.json"):
        d = json.load(open(f))
        rid = next(k for k in pre["runs"] if k.startswith(str(d["rollout_id"])[:8]))
        grade = pre["runs"][rid]["grade"]["subscores"]
        d["_graded"] = {k: v for k, v in grade.items() if re.match(rf"{g}\.r\d\.", k)}
        d["_reward"] = grade.get("reward")
        never = (g, d["run"]) in A.NEVER_SHIPPED
        for l in d.get("lost_facts", []):
            o = A.OVERRIDES.get((g, d["run"], l["fact"]))
            if o:
                l["cause"] = o
            if never:
                l["cause"] = "never_shipped"
        causes = [l["cause"] for l in d.get("lost_facts", [])]
        d["_dead"] = never or (bool(causes) and all(c == "infra" for c in causes) and not d.get("passed_facts"))
        runs.append(d)
    return meta, plant, runs


def main():
    tasks = [g for g in T if glob.glob(f"{S}/readers/{g}/run*.json")]
    L = ["# Cross-task synthesis (generated by synth.py)", "",
         f"tasks with reader output: {tasks}; pooled rates exclude {sorted(THIN) or 'nothing'}", ""]

    # 1. per-task scoreboard
    L += ["## Scoreboard", "", "| task | runs read | shipped & live | mean reward (live) | mean reward (all graded) | at 1.00 | dead runs |",
          "|---|---|---|---|---|---|---|"]
    pool = {}
    for g in tasks:
        meta, plant, runs = load(g)
        pool[g] = (meta, plant, runs)
        live = [d for d in runs if not d["_dead"]]
        graded = [d for d in runs if d["_reward"] is not None]
        mr = sum(d["_reward"] or 0 for d in live) / len(live) if live else float("nan")
        ma = sum(d["_reward"] or 0 for d in graded) / len(graded) if graded else float("nan")
        L.append(f"| {g} | {len(runs)} | {len(live)} | {mr:.2f} | {ma:.2f} | {sum((d['_reward'] or 0) >= 0.999 for d in runs)} | "
                 f"{sorted((d['run'], d.get('eval', '')) for d in runs if d['_dead'])} |")

    pooled = {g: v for g, v in pool.items() if g not in THIN}

    # 2. causes
    cause_t = collections.Counter()
    L += ["", "## Lost fact-points by cause (live runs only; knowledge causes)", "", "| task | " + " | ".join(sorted(KNOWLEDGE)) + " | total |", "|---" * (len(KNOWLEDGE) + 2) + "|"]
    for g, (meta, plant, runs) in pool.items():
        c = collections.Counter(l["cause"] for d in runs if not d["_dead"] for l in d.get("lost_facts", []) if l["cause"] in KNOWLEDGE)
        if g not in THIN:
            cause_t.update(c)
        L.append(f"| {g}{' (thin)' if g in THIN else ''} | " + " | ".join(str(c.get(k, 0)) for k in sorted(KNOWLEDGE)) + f" | {sum(c.values())} |")
    tot = sum(cause_t.values())
    L += ["", "**pooled:** " + ", ".join(f"{k} {v} ({100 * v / tot:.0f}%)" for k, v in cause_t.most_common())]
    dead = collections.Counter(l["cause"] for g, (m, p, runs) in pooled.items() for d in runs if d["_dead"] for l in d.get("lost_facts", []))
    L += [f"**points in dead runs (excluded above):** {dict(dead)}", ""]

    # 3. fact-field difficulty (Horizon grades, live runs)
    fld = collections.defaultdict(lambda: [0, 0])
    for g, (meta, plant, runs) in pooled.items():
        for d in runs:
            if d["_dead"]:
                continue
            for k, v in d["_graded"].items():
                f = k.split(".", 2)[2]
                fld[f][0] += v == 1
                fld[f][1] += 1
    L += ["## Fact-field difficulty (pooled, live runs)", "", "| field | passed |", "|---|---|"]
    L += [f"| {f} | {pct(a, b)} |" for f, (a, b) in sorted(fld.items(), key=lambda x: x[1][0] / x[1][1])]

    # 4. findability by quality
    b = collections.defaultdict(lambda: [0, 0])
    reg = collections.defaultdict(lambda: [0, 0])
    for g, (meta, plant, runs) in pooled.items():
        for d in runs:
            if d["_dead"]:
                continue
            for r in d["remarks"]:
                m = meta.get(r["id"])
                if not m:
                    continue
                seen = A.norm_found(r.get("found")) != "no"
                pc = plant.get(r["id"], {})
                keys = [f"surface={m.get('surface')}", f"kind={m['kind']}", f"literal={'yes' if m.get('literal') else 'no'}",
                        f"carrier={pc.get('carrier_kind')}"]
                if m.get("surface") == "chat":
                    keys.append(f"channel={m.get('where')}")
                for k in keys:
                    b[k][0] += seen
                    b[k][1] += 1
                if seen and m["kind"] == "clue":
                    reg["registered"][0] += str(r.get("registered", "")).startswith("requirement")
                    reg["registered"][1] += 1
                    reg["followed"][0] += str(r.get("acted", "")).startswith("followed")
                    reg["followed"][1] += 1
    L += ["", "## Findability by remark quality (pooled, live runs; found = yes or partial)", "", "| bucket | found |", "|---|---|"]
    for prefix in ("surface=", "kind=", "literal=", "carrier=", "channel="):
        rows = [(k, v) for k, v in b.items() if k.startswith(prefix)]
        L += [f"| {k} | {pct(*v)} |" for k, v in sorted(rows, key=lambda x: x[1][0] / max(x[1][1], 1))]
    L += ["", f"**found clues registered as a requirement:** {pct(*reg['registered'])}; **followed by the shipped code:** {pct(*reg['followed'])}", ""]

    # 5. herrings
    h = collections.Counter()
    hid = lambda g, s: (re.search(rf"{g}\.r\d\.[\w-]+", str(s)) or re.search(r"\S+", str(s))).group(0)
    L += ["## Herrings (pooled, live runs)", ""]
    for g, (meta, plant, runs) in pooled.items():
        for d in runs:
            if d["_dead"]:
                continue
            for x in d.get("herrings", []):
                h["pairs"] += 1
                h["saw_herring"] += A.yes(x.get("saw_herring"))
                h["saw_reversal"] += A.yes(x.get("saw_reversal"))
                h["saw_herring_not_reversal"] += A.yes(x.get("saw_herring")) and not A.yes(x.get("saw_reversal"))
                h["believed_herring"] += str(x.get("believed", "")).lower().startswith("herring")
                h["code_followed_herring"] += x.get("code_followed_herring") is True
    n = h["pairs"]
    L += [f"- (run, herring) pairs: {n}", f"- saw the herring: {pct(h['saw_herring'], n)}", f"- saw its reversal: {pct(h['saw_reversal'], n)}",
          f"- saw the herring but not its reversal: {pct(h['saw_herring_not_reversal'], n)}",
          f"- believed the herring: {pct(h['believed_herring'], n)}", f"- shipped code followed the herring: {pct(h['code_followed_herring'], n)}", ""]

    open(f"{S}/synth.md", "w").write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
